# Generated by Django 2.0 on 2018-07-11 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_count', '0002_readnum_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum_detail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
