# Generated by Django 2.0 on 2018-07-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180706_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='the_blog',
        ),
        migrations.DeleteModel(
            name='Readnum',
        ),
    ]
